### ISSUE TITLE
regex sequence filter

### ISSUE THREAD

**Issue by KyleStiers** [lafita/mmtf-fragment-search#4]
I'm still sorting through issues with getting this to build on windows (a few modules of the mmtf-spark project don't build successfully during the maven install). 

Just so you know, once I have those sorted out, I'm going to try to implement/modify the regex filter (ContainsSequenceRegex) so that users can further filter fragments by sequence if they so choose. 

Something akin to: `.filter(new ContainsSequenceRegex("[XXX].{1}[XXX].{1}[XXX]."))` after the call to ConsecutiveFragment() in the creation of the JavaRDD `rows` variable. I'm not very familiar with regex though. So it could take me a bit.

**Comment by lafita** [comment]
Have you tried skipping the tests when running the maven install?

**Comment by KyleStiers** [comment]
Yes, I've forced it to skip tests / ignore failures and that makes it build successfully. It still doesn't run properly, I get: 
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.biojava.nbio.structure.StructureImpl.getChainByIndex(StructureImpl.java:353)
	at org.biojava.nbio.structure.StructureImpl.getChainByIndex(StructureImpl.java:345)
	at edu.sdsc.main.FragmentSearch.main(FragmentSearch.java:41)
```
However, one of the tests that fails (maybe 2) are used in FragmentSearch.java and so I'm wondering if that's responsible. It seems like BioJava isn't working properly, as that error seems to come from the `.toArray` method of the AminoAcid `query `instance.
